- name: ServiceNow CI/CD Run ATF Test Suite
  # You may pin to the exact commit or the version.
  # uses: ServiceNow/sncicd-tests-run@49e9a72f68d0d1a2501d24a2cb14ed31b32a9ea8
  uses: ServiceNow/sncicd-tests-run@2.0.0
  with:
    # Name of the browser to use to run the client test. 
    browserName: # optional
    # Starting value of the version of the browser specified in browser_name to use to run the test. For example, if you enter '9', that would enable all 9.x.x.x versions
    browserVersion: # optional
    # Name of the operating system under which to run the test suite.
    osName: # optional
    # Starting value of the version of the operating system under which to run the test suite. For example, if you enter '8', that would enable all 8.x.x.x versions.
    osVersion: # optional
    # Required if testSuiteName is not specified
    testSuiteSysId: # optional
    # Required if testSuiteSysId is not specified
    testSuiteName: # optional
